included:
    - Projects
excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
    - Projects/App/Sources/AppDelegate.swift
    - Projects/App/Sources/SceneDelegate.swift
    - Projects/Feature/**/Demo/AppDelegate.swift
    - Projects/Feature/**/Demo/SceneDelegate.swift
    - Tuist
    - Derived
    - Plugins
    - XCConfig
identifier_name:
    min_length:
        warning: 2
        error: 3
    excluded: # 제외할 문자열 목록
        - f
        - ws
        - my
function_body_length:
    warning: 150
    error: 300
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 2000
line_length:
    warning: 80
    error: 400
disabled_rules: # 제외하고 싶은 룰
    - trailing_whitespace
    - type_name
    - trailing_comma
#    - conditional_returns_on_newline
#    - identifier_name
#    - nesting
#    - colon
#    - control_statement
#    - vertical_parameter_alignment
#    - cyclomatic_complexity
#    - void_function_in_ternary
#    - comment_spacing
#    - function_parameter_count
opt_in_rules:
    - empty_string
#    - conditional_returns_on_newline
