name: PullRequestTest

on:
  pull_request:
    branches:
      - release
jobs:
  build_test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2

      - name: Bring ignored files
        uses: actions/checkout@v3
        with:
          repository: Pepsi-Club/WhereMyBus-ignored
          path: XCConfig/
          token: ${{ secrets.ACTION_TOKEN }}
                    
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2.0"
          
      - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
            swift-version: "5.9.0"
        
      - name: Get swift version
        run: swift --version
        
      - name: Install Tuist
        run: curl -Ls https://install.tuist.io|bash

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Tuist Clean
        run: tuist clean

      - name: Tuist Fetch
        run: tuist fetch

      - name: Tuist Build Test
        run: tuist build
