name: PullRequestTest

on:
  pull_request:
    branches:
      - dev
      
jobs:
  build_test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2

      - name: Bring ignored files
        uses: actions/checkout@v3
        with:
          repository: Pepsi-Club/WhereMyBus-ignored
          path: XCConfig/
          token: ${{ secrets.ACTION_TOKEN }}
                    
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.3"
          
      - name: Setup Swift Version
        uses: swift-actions/setup-swift@v2
        with:
            swift-version: "5.10"
        
      - name: Get swift version
        run: swift --version
        
      - name: Install Tuist
        run: curl -Ls https://install.tuist.io|bash

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Tuist Clean
        run: tuist clean

      - name: Tuist Fetch
        run: tuist fetch

      - name: Tuist Build Test
        run: tuist build App
